### ISSUE TITLE
RHS Table of Contents Menu

### ISSUE THREAD

**Issue by andytudhope** [kernel-community/kernel-v2#1]
**Is your feature request related to a problem? Please describe.**

I think that the text is actually less readable if it goes all the way to the right hand edge on desktop. It _feels_ like there is just too much to take in and the added wideness can be intimidating. Moreover, many of the Curated Briefs are quite long and it is a really nice feature to be able to move quickly to a specific subsection in them, which requires a ToC menu on the right side.

**Describe alternatives you've considered**
Having no ToC, as currently is the case. Not ideal for the reasons mentioned above.

**Describe the solution you'd like**

1. Every subheading, down to `h5` should be added to a ToC on the right hand side of the page on desktop views.
2. h1 and h2 subheadings must be in **bold**, other subheadings normal text.
3. Each heading level down must be indented one `rem` further in. That is:
```
h1
-----h2
----------h3
---------------h4
etc.
```
3. However, the menu should be flush to left of its box, beginning with the biggest heading for that file. That is, even if there are only h2s and h3s, don't begin rendering the h2s `1rem` in. Start with the biggest in that file and indent from there.
4. Each subheading needs to be clickable and to take you to the appropriate section of the file. They should be the colour of normal text though, not links.
4. This should be a feature we can toggle on and off in the frontmatter of each file.
5. It should disappear without a trace on mobile screens.
6. The ToC menu should have a width of ~`12rem` and padding ~`1.2rem` or equivalent in `fr`, which is the measure we use on this new site afaik.

**Screenshots and Additional context**

It should look as close as possible to the [current ToC](https://kernel.community/module-5/prosocial-value/)

![Screenshot from 2021-03-24 17-54-56](https://user-images.githubusercontent.com/13001517/112341566-31b28e80-8cca-11eb-82a1-3e6c431edb88.png)

**Comment by andytudhope** [comment]
Moving this to Milestone 2, as it requires some design work and so will be accounted for at a different rate.

In addition to this, we are hoping to make sure that leveraging the heading anchor links on each page can be used to make the search function more precise, as it is on the current site (i.e. it shouldn't just take you to the page where you search word appears, but the specific section on that page).

**Comment by MaximumCrash** [comment]
Completed by #38
