### ISSUE TITLE
Blog Content

### ISSUE THREAD

**Issue by andytudhope** [kernel-community/kernel-v2#10]
**Is your feature request related to a problem? Please describe.**
The current blog contains only example content.

**Describe the solution you'd like**
I'd like to launch the new site with some great posts in at least two different categories, so we can encourage people in #writers-corner with somewhere awesome to showcase their work during kb3.

**Describe alternatives you've considered**
Launching without the blog visible. This remains an option.

This is really a work ticket for @vs77bb

**Comment by vs77bb** [comment]
Excited for this. We do have one important post today: https://blog.kernel.community/post/launching-kb3/

Thinking through what else we might add. I have some ideas and love the #writers-corner one as well.

**Comment by andytudhope** [comment]
We've launched and have some blog content - will be trying to encourage kb3 fellows to contribute further this block.
