### ISSUE TITLE
UI/UX improvement Kernel community website

### ISSUE THREAD

**Issue by KukretiShubham** [kernel-community/kernel-v2#183]
**Is your feature request related to a problem? Please describe.**
Current Dark and light theme switch looks like this. 
![image](https://user-images.githubusercontent.com/57281769/141669827-cec2f6f7-f1db-43ea-adb2-2d98693d69e7.png)

**Describe the solution you'd like**
I suggest to something like this. 
![image](https://user-images.githubusercontent.com/57281769/141669972-f3301a93-9e78-4abf-8fdf-0a9b9bd81155.png)

**Comment by andytudhope** [comment]
I am happy with the current implementation, though I appreciate you taking the time to open this.
