### ISSUE TITLE
404 on "Play of Pattern" link in notion doc 

### ISSUE THREAD

**Issue by coltonbrwn** [kernel-community/kernel-v2#185]
![image](https://user-images.githubusercontent.com/1873024/142259414-f9b52257-d4cb-441a-bb1d-f5a9de8091c0.png)

The aforementioned link: https://kernel.community/module-0/play-of-pattern/ gives a 404 
Notion doc here: https://www.notion.so/Learn-a91eaa8b679c4780ab642ac1b3afefc6

Will dig in to see if I can fix it, but wanted to track here!

**Comment by andytudhope** [comment]
My apologies that it has taken me so long to attend to this, and thanks for noticing :pray:
