### ISSUE TITLE
Logos and Favicon

### ISSUE THREAD

**Issue by andytudhope** [kernel-community/kernel-v2#2]
**Is your feature request related to a problem? Please describe.**

Very simple: let's update the logos and favicons.

**Describe the solution you'd like**

Get a dynamic version of the kernel seed for the favicon and for the header logo. Consider asking Guist or someone else to design a nice footer logo.

Perhaps a good first issue for @nglglhtr to get familiar with things

**Comment by MaximumCrash** [comment]
Closed by #19
