### ISSUE TITLE
Headings Missing Line Breaks

### ISSUE THREAD

**Issue by andytudhope** [kernel-community/kernel-v2#25]
**Describe the bug**

After changing the font face to something which is legal, all our headings no longer have proper line breaks, margins etc.

**To Reproduce**
1. Go to the home page, or any one of the pages in `Learn`.
3. Scroll down to any heading.

**Expected behavior**

Proper top and bottom margins and line breaks after all headings.

**Screenshots**

![Screenshot from 2021-04-26 09-50-59](https://user-images.githubusercontent.com/13001517/116290366-ac703d00-a793-11eb-9a94-c0b501169fc2.png)

**Additional context**

This is specifically for the work in #19

**Comment by MaximumCrash** [comment]
Closed by #19
