### ISSUE TITLE
Improve Search Block Styles

### ISSUE THREAD

**Issue by andytudhope** [kernel-community/kernel-v2#26]
**Is your feature request related to a problem? Please describe.**

The way that search results are styled is not clear and could be improved. See the screenshot below:

![Screenshot from 2021-04-26 09-52-00](https://user-images.githubusercontent.com/13001517/116291263-aa5aae00-a794-11eb-809d-c144352e8b59.png)

**Describe the solution you'd like**

I just want two things to happen here, so there is not even a need for a design imo. 

1. Insert a line break between the title of the page which any search finds and its metadata. 
2. Make sure the metadata description is `400`, not `600` (leaving the title `600`).

**Describe alternatives you've considered**

It might be worth making the page description 1pt smaller, but I leave this to a designer's eye and better judgment.

**Comment by MaximumCrash** [comment]
Closed by #19
