### ISSUE TITLE
Primary and Secondary buttons have different padding when icons are involved

### ISSUE THREAD

**Issue by andytudhope** [kernel-community/kernel-v2#3]
**Describe the bug**

It's in the title: the padding on buttons with icons is different. Makes it difficult if you want to have two inline buttons next to each other, one with an internal link, one with an external one.

**To Reproduce**
1. Go to localhost:8000/en
2. Click on Look at the two buttons on the home page, above the fold

**Expected behavior**

Inline buttons should always be perfectly aligned.

**Screenshots**

![Screenshot from 2021-03-24 18-16-23](https://user-images.githubusercontent.com/13001517/112344740-15fcb780-8ccd-11eb-9cd4-b5e242a5f790.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 86.0.1

**Comment by MaximumCrash** [comment]
Completed by #19
