### ISSUE TITLE
Listening society link on the module6/censorship resistance page results in a 404

### ISSUE THREAD

**Issue by eleventh19** [kernel-community/kernel-v2#395]
**Describe the bug**
The link for the [listening society](https://www.kernel.community/en/learn/module-6/listening-stories/#infinite-games-in-a-listening-society) reading in the [censorship resistance](https://www.kernel.community/en/learn/module-6/censorship-resistance/) page within module 6 results in a 404

**To Reproduce**
1. Go to https://www.kernel.community/en/learn/module-6/censorship-resistance/
2. Click on '[listening society](https://www.kernel.community/en/learn/module-6/listening-stories/#infinite-games-in-a-listening-society)' in the first paragraph  
3. See error

**Expected behavior**
Going to the listening society reading 

**Screenshots**
<img width="684" alt="Screen Shot 2022-07-11 at 8 07 28 PM" src="https://user-images.githubusercontent.com/595464/178378917-9da0f83e-5d00-4571-94e2-dcb7754c8d34.png">

**Desktop (please complete the following information):**
 - OS: Monterey 12.4
 - Browser: Brave 
 - Version: 1.39.120 Chromium: 102.0.5005.99 (Official Build) (x86_64)](https://brave.com/latest/

**Additional context**

**Comment by andytudhope** [comment]
Thank you for noticing :heart: 

This was fixed by a saint in #400
