### ISSUE TITLE
Fully Update Colour Palette

### ISSUE THREAD

**Issue by andytudhope** [kernel-community/kernel-v2#4]
**Describe the solution you'd like**

It is a happy coincidence that the Maker Comm-Dev team and Kernel share very similar colour palettes. However, we need to check through everything and make the slight changes required to both light and dark mode to reflect the Kernel colours accurately.

**Comment by MaximumCrash** [comment]
@andytudhope This has been started by #19, but I imagine folks will want things to be tweaked over time. Let me know if the new changes meet your needs and we can close this.

**Comment by MaximumCrash** [comment]
Closed by #19
