### ISSUE TITLE
No Menu Icon on Mobile Light Screen

### ISSUE THREAD

**Issue by andytudhope** [kernel-community/kernel-v2#68]
**Describe the bug**

When light/white screen is selected on mobile view, no menu item appears.

**To Reproduce**
1. Go to https://kernel.community/en
2. Use any mobile phone
3. See the lack of a menu item.

**Expected behavior**
A black hamburger menu should appear. See the dark screen for the expected behaviour.

**Screenshots**

![Screenshot from 2021-06-08 17-33-16](https://user-images.githubusercontent.com/13001517/121214698-a8016e80-c87f-11eb-8923-c0d2811a0372.png)

**Smartphone (please complete the following information):**
 - Device: Huawei
 - OS: Android 10
 - Browser: Brave

**Comment by sharonsheah** [comment]
Hi! Could I be assigned to this? 🙂  I came up with a solution.

**Comment by andytudhope** [comment]
Hi @sharonsheah - sure thing, please go ahead and submit and we can talk about some kind of reciprocal action :pray:

**Comment by sharonsheah** [comment]
I can't seem to push my branch up to make a pull request 🙁  Where do I submit exactly?
