### ISSUE TITLE
Flashcard v1 Component

### ISSUE THREAD

**Issue by andytudhope** [kernel-community/kernel-v2#7]
### Describe the solution you'd like

We need to develop great, clear, delightful flashcards to present critical concepts in a memorable way. To do this, we will be taking our design inspiration directly from [Quantum Country](https://quantum.country/qcvc). We don't have a good design resource atm, so we're literally going to copy exactly what is already on QC. Requirements:

1. Card is centred on the page. ~30% width for desktop, ~80% width on mobile.
2. Rounded borders, elegant box-shadow, white text, Kernel dark blue background (#212145)
3. Card is split in half: top half shows a question. Bottom half is blurred out and reveals the answer when clicked on.
4. Beneath the answer are two buttons: "Remembered" and "Didn't Remember", with icons as below.
5. If remembered, card transitions to light green background, black text (#00FC9C).
6. If forgotten, card transitions to warning background, black text (#FFBA44) 

### Screenshots and Additional context

**Stage 1:**

![Screenshot from 2021-03-31 12-56-37](https://user-images.githubusercontent.com/13001517/113133986-94eb7600-9220-11eb-8f87-73dc0ab0270f.png)

**Stage 2:**

![Screenshot from 2021-03-31 12-57-41](https://user-images.githubusercontent.com/13001517/113134095-b51b3500-9220-11eb-8e05-494b249f4206.png)

**Notes:**

1. No need to track time for this iteration, as is being done at the bottom of the cards in the screenshots above.
2. On QC, flashcards are stackable, hence the slight design difference between single cards and stacks. Let's develop with this in mind, as there are stages in Kernel where I want to stack cards too.
3. Once you have completed the first stack there, they grey out the content side of the screen and introduce you to how the system works now that you have a real taste of it. This is really cool. We should factor it into how we think about our designs from the start.

![Screenshot from 2021-03-31 13-02-33](https://user-images.githubusercontent.com/13001517/113134808-949faa80-9221-11eb-9acb-becd2b9e5a6b.png)

4. it's even more slick on mobile, where they grey the screen and drop a modal in from the top :heart_eyes: 

![image](https://user-images.githubusercontent.com/13001517/113135211-24ddef80-9222-11eb-9668-2a7a1ee70304.png)

**Comment by MaximumCrash** [comment]
Tested out your spec and tweaked it a bit to work better between light and dark modes. 

Completed by #38
