### ISSUE TITLE
Fellows Homepage Section

### ISSUE THREAD

**Issue by andytudhope** [kernel-community/kernel-v2#71]
**Is your feature request related to a problem? Please describe.**

No. We simply need to add a new Fellows Section to the Home Page. The designs for doing so are here: https://www.figma.com/file/8bKVXDz8qsJ8jLYYBWzW8X/KERNEL-Graphics?node-id=863%3A0

**Describe the solution you'd like**

This is actually quite easy to implement given the components we have already.

1. We use an all-contributorssrc file, which produces and all-contributors.json file at build time that is used to populate the `<Authors all>` tag wherever it is included in the site.
2. Remove the all-contributorssrc and associated script - we no longer need them.
3. Repurpose the existing component to show Fellows rather than the old contributors, and then add all the Fellows to that file (which I can do myself).
3. What is required for this issue is overhauling the current styling on the `<Fellows all>` from using the current grid, to match the styles specified on the Landing Page in the above link. 
4. The styling for this also pretty much exists in the `BlogAuthors` component, we'd just need to alter the padding a little to fit more faces on the page.

**Describe alternatives you've considered**

We could build a whole new component from scratch, but most of the pieces we need already exist - just have to make them play nicely together.

**Screenshots and Additional context**

Check the LP page in the above Figma link. You're looking for this section.

![Screenshot from 2021-06-08 18-16-12](https://user-images.githubusercontent.com/13001517/121221794-3678ee80-c886-11eb-9af3-40083696850c.png)

**Comment by andytudhope** [comment]
The schema for the `all-fellows.json` file should be:
```
{
  "fellows": [
    {
      "name": "Simona Pop",
      "url": "https://twitter.com/Sim_Pop",
      "image": "https://kernel.community/images/projects/swivel.jpg" 
    },
    { ...more fellows
    },
}
```

**Comment by probablyangg** [comment]
do we need an api call for it or a static json?

**Comment by nglglhtr** [comment]
there you go! https://gist.github.com/nglglhtr/222f1f0d0c2370ebc19d00d03ffdbd22

^ that's all the data from notion for each fellow since genesis filtered for presence of both a social link and image url. Since I'm filtering on both these properties we're missing genesis block people because we never collected their images

**Comment by probablyangg** [comment]
make sure to add a filter or check the array for valid urls before embedding - we might have some with just twitter/github handles
