### ISSUE TITLE
404 trying to reach "Getting Started"

### ISSUE THREAD

**Issue by IPalos** [kernel-community/kernel-v2#81]
The page [KERNEL Learn Track](https://kernel.community/getting-started/) redirects to a 404

1. Go to https://www.notion.so/What-is-KERNEL-b9520eb29d954f5fb709150cae3975b1
2. Click on KERNEK Learn Track
4. See 404 error

Expected behavior:
See a "Getting Started" page

**Comment by andytudhope** [comment]
Fixed, apologies for the long delay and thanks so much for finding this :heart:
