### ISSUE TITLE
link to learner track is broken.

### ISSUE THREAD

**Issue by evanxuw** [kernel-community/kernel-v2#83]
**Describe the bug**

the link to the kernel learner track is broken. 

https://kernel.community/getting-started/

**To Reproduce**
1. Go to 'https://www.notion.so/What-is-KERNEL-b9520eb29d954f5fb709150cae3975b1 
2. Scroll down to 'KERNEL TRACK'
3. Click on Kernel Learn Track.

**Expected behavior**

correct the link 

**Screenshots**
![image](https://user-images.githubusercontent.com/75350091/123672678-759abf80-d7f4-11eb-9aa9-f0f8335060e1.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by andytudhope** [comment]
Fixed in #81 - thanks for noting this :heart:
