### ISSUE TITLE
link to "promised Bret Victor video is broken"

### ISSUE THREAD

**Issue by mariorz** [kernel-community/kernel-v2#84]
**Describe the bug**
On the intro to module 6, the link described as "the promised Bret Victor video from Week 1" is broken and returns a 404

**To Reproduce**
1. Go to https://kernel.community/en/learn/module-6/
2. Click on 'promised Bret Victor video from Week 1"
3. Look at the rendered html
4. See 404 error and no video :(

**Expected behavior**
I expected to get a Bret VIctor presentation of some sort.

**Comment by andytudhope** [comment]
Thank you for finding this. I fixed it in https://github.com/kernel-community/kernel-v2/commit/9916be488f4a5378bda412225c701101746e6150

Really appreciate the close reading :heart:
